### ISSUE TITLE
Can't remove contact from all groups

### ISSUE THREAD

**Issue by webnard** [dialmycalls/php-sdk-v2#1]
With the current client it is impossible to remove a contact from all groups. Setting `UpdateContactByIdParameters->groups` to `null`, `[]`, `false`, and `0` all do nothing.

**Comment by snellingio** [comment]
Hey @webnard, thanks for the report. 

After doing some testing, you are correct. DialMyCalls currently does not support deleting groups from a particular contact via the API. 

I definitely understand this is less than ideal. A work around for the time being is to delete the contact and re-create the contact.

If you don't mind me asking, what's your use case for this?

**Comment by webnard** [comment]
@snellingio Use case is just users entering and leaving groups. I'm manipulating users' groups programmatically, and it's just easier to not have to check whether or not the set is empty and instead just push it regardless. Fewer code branches is all.

```
set a = {g1, g2, g3}
a.remove(g1, g2)
a.push(g4)
update_groups(a)

set b = {g1, g2, g3}
b.remove(g1,g2,g3)
b.push()
update_groups(b) // FAILS
```
