### ISSUE TITLE
Allow for retrieving contact by phone number

### ISSUE THREAD

**Issue by webnard** [dialmycalls/php-sdk-v2#2]
Are there any plans to allow the retrieval of a contact by their phone number? Right now that's all we're storing locally, so looking up a contact in DMC requires paging through every single contact we have until we find one with a matching phone number.

**Comment by snellingio** [comment]
I think the preferred way to do this currently is to store the contact uuid in your database, and then just pass those in when needed. Paging through all the contacts to find a match does not seem like an efficient way to do this.
