### ISSUE TITLE
I am getting 500 while creating text messages and call

### ISSUE THREAD

**Issue by noorkaximi** [dialmycalls/php-sdk-v2#3]
I am trying to create text messages and call but it's giving me 500 response 

>  [500] Error connecting to the API (https://api.dialmycalls.com/2.0/service/text)

```
 $api_instance = new \DialMyCalls\Api\Texts();
                                $createTextParameters = new \DialMyCalls\Models\CreateTextParameters(); // \DialMyCalls\Models\CreateTextParameters | Request body
                                $createTextParameters["name"] = "Registration Text";
                                $createTextParameters["KeywordId"] =$keyword_id;
                                $createTextParameters["messages"] = array("Hello, Welcome To Demo. Testing Messages");
                                $createTextParameters["sendImmediately"] = true;
                                $createTextParameters["contacts"] = ["phone" => "1111111111"];
try {
                                    $result = $api_instance->createText($createTextParameters);
                                    print_r($result);
                                } catch (Exception $e) {
                                    echo 'Exception when calling Texts->createText: ', $e->getMessage(), PHP_EOL;
                                }
```

**Comment by mfreedman** [comment]
It sounds like you're possibly having SSL issues connecting to us.

You can try something like:

`DialMyCalls\Configuration::getDefaultConfiguration()->setSSLVerification(false);`

**Comment by noorkaximi** [comment]
just turn on debug and here is the output
[DEBUG] HTTP Request body ~BEGIN~ ~END~
*Warning*: curl_setopt(): cannot represent a stream of type Output as a
STDIO FILE* in
*E:\xampp\htdocs\dial-my-call\vendor\dialmycalls\php-sdk-v2\src\ApiClient.php*
on
line *226*
[DEBUG] HTTP Response body ~BEGIN~
{"results":[{"id":"fb837b56-4433-11ea-b2f8-0cc47ab3cb58","name":"TestCall","type":"sound","seconds":5,"url":"https:\/\/
dhee6yzy496a9.cloudfront.net
\/981101\/d6a29026f73b8819eaf2ca2efbca3b57.mp3","processed":true,"created_at":"2020-01-31T14:14:24+0000","updated_at":"2020-01-31T14:14:24+0000","deleted":false},{"id":"1d460382-43dd-11ea-bbab-0cc47ab3cb58","name":"Mike","type":"text","seconds":2,"url":"https:\/\/
www.dialmycalls.com\/recordings-v2\/d3\/42\/fa\/d342fa20-b7f3-5ffc-8a52-0bd424e54975.mp3","processed":true,"created_at":"2020-01-31T03:52:34+0000","updated_at":"2020-01-31T03:52:34+0000","deleted":false}],"meta":{"result":"success","status":200,"request_id":"0bf72042-4479-11ea-afdd-0cc47ab3cb58"}}
~END~ [DEBUG] HTTP Request body ~BEGIN~ ~END~
*Warning*: curl_setopt(): cannot represent a stream of type Output as a
STDIO FILE* in
*E:\xampp\htdocs\dial-my-call\vendor\dialmycalls\php-sdk-v2\src\ApiClient.php*
on
line *226*
[DEBUG] HTTP Response body ~BEGIN~
{"results":[{"id":"54faa74e-4430-11ea-9d8e-0cc47ab3cb58","name":"AAINC","phone":"5158092251","approved":true,"created_at":"2020-01-31T13:48:16+0000","updated_at":"2020-01-31T13:48:16+0000"},{"id":"e700bab8-442e-11ea-8b3d-0cc47ab3cb58","name":"Noor","phone":"3193325106","approved":true,"created_at":"2020-01-31T13:38:02+0000","updated_at":"2020-01-31T13:38:02+0000"}],"meta":{"result":"success","status":200,"request_id":"0cb88976-4479-11ea-96b3-0cc47ab3cb58"}}
~END~ [DEBUG] HTTP Request body ~BEGIN~ {"name":"AAINC Registration
Call","callerid_id":"54faa74e-4430-11ea-9d8e-0cc47ab3cb58","recording_id":"fb837b56-4433-11ea-b2f8-0cc47ab3cb58","send_immediately":true,"contacts":{"phone":"3193325106"}}
~END~
*Warning*: curl_setopt(): cannot represent a stream of type Output as a
STDIO FILE* in
*E:\xampp\htdocs\dial-my-call\vendor\dialmycalls\php-sdk-v2\src\ApiClient.php*
on
line *226*
[DEBUG] HTTP Response body ~BEGIN~ {"results":{"error":"Internal error. Try
again
later."},"meta":{"result":"failure","status":500,"request_id":"0d769ccc-4479-11ea-86bb-0cc47ab3cb58"}}
~END~ Exception when calling Calls->createCall: [500] Error connecting to
the API (https://api.dialmycalls.com/2.0/service/call) [DEBUG] HTTP Request
body ~BEGIN~ ~END~
*Warning*: curl_setopt(): cannot represent a stream of type Output as a
STDIO FILE* in
*E:\xampp\htdocs\dial-my-call\vendor\dialmycalls\php-sdk-v2\src\ApiClient.php*
on
line *226*
[DEBUG] HTTP Response body ~BEGIN~
{"results":[{"id":"5a172ee6-1082-11ea-a308-0cc47ab3cb58","keyword":"DMC4Z2D7","status":"active","created_at":"2019-11-26T19:24:23+0000","updated_at":"2019-11-26T19:24:23+0000"}],"meta":{"result":"success","status":200,"request_id":"0e347134-4479-11ea-926a-0cc47ab3cb58"}}
~END~ object(DialMyCalls\Models\CreateTextParameters)#17 (1) {
["container":protected]=> array(11) { ["name"]=> string(23) "AAINC
Registration Text" ["keywordId"]=> NULL ["messages"]=> array(1) { [0]=>
string(41) "Hello, Welcome To AAINC. Testing Messages" } ["sendAt"]=> NULL
["sendImmediately"]=> bool(true) ["sendEmail"]=> NULL ["accessaccountId"]=>
NULL ["shortcodeId"]=> NULL ["concatenateSms"]=> NULL ["contacts"]=>
array(2) { ["phone"]=> string(10) "3193325106" ["fname"]=> string(4) "noor"
} ["KeywordId"]=> string(36) "5a172ee6-1082-11ea-a308-0cc47ab3cb58" } }
[DEBUG] HTTP Request body ~BEGIN~ {"name":"AAINC Registration
Text","messages":["Hello, Welcome To AAINC. Testing
Messages"],"send_immediately":true,"contacts":{"phone":"3193325106","fname":"noor"}}
~END~
*Warning*: curl_setopt(): cannot represent a stream of type Output as a
STDIO FILE* in
*E:\xampp\htdocs\dial-my-call\vendor\dialmycalls\php-sdk-v2\src\ApiClient.php*
on
line *226*
[DEBUG] HTTP Response body ~BEGIN~ {"results":{"error":"Internal error. Try
again
later."},"meta":{"result":"failure","status":500,"request_id":"0ef7ded0-4479-11ea-bcd6-0cc47ab3cb58"}}
~END~ Exception when calling Texts->createText: [500] Error connecting to
the API (https://api.dialmycalls.com/2.0/service/text)

**Comment by noorkaximi** [comment]
DialMyCalls\Configuration::getDefaultConfiguration()->setSSLVerification(false);
it didn't helped me... still getting the same error

**Comment by noorkaximi** [comment]
> It sounds like you're possibly having SSL issues connecting to us.
> 
> You can try something like:
> 
> `DialMyCalls\Configuration::getDefaultConfiguration()->setSSLVerification(false);`
i added it but it didn't help me kindly tell me what could be other possible issues

**Comment by mfreedman** [comment]
Is this error still happening?

**Comment by noorkaximi** [comment]
Yes

**Comment by mfreedman** [comment]
Since you also have a ticket open with our API support I'm going to close this issue.
